### ISSUE TITLE
Close Session

### ISSUE THREAD

**Issue by Reddriver** [rticau/Suds2Library#1]
Hi, I have dotzen test cases each with its Create Session to another endpoint. It consumes a lot of system resources. I noticed that clients are exist between test cases. I think that is not good solution. Better way could be close session between TCs, if you do not want to close the session, you can create the session inside Test Suite Setup. Or you can create keyword Close Session (release the system resources)

**Comment by rticau** [comment]
Hi @Reddriver. Would it be possible for you to provide a very simple example that can be used to quickly reproduce the issue?

**Comment by Reddriver** [comment]
The main problem is when I use DataDriver https://github.com/Snooz82/robotframework-datadriver
Every test only creates Soap Client for demonstation. It takes about 80-100 MBs RAM per TC.  When I use my own keyword written in Python (request library) for calling SOAP directly, it consumes only few MBs.

```
*** Settings ***
Resource  ../Resources/Common.resource
Library  DataDriver  file=../Data/SOAP.csv  encoding=UTF-8
Test Template  OK call
Test Setup  Extract informations of service

*** Keywords ***
OK call
    [Arguments]  ${platform}
    Create Soap Client  ${EXECDIR}/Resources/WSDL/MW_${WSDL}/structured/WS_MW_${WSDL}.wsdl

*** Test Cases ***
MW_CgpService_getClientPositionExtended_v03_01
    OpenShift

```

**Comment by ricualex** [comment]
Hi @Reddriver, 
I couldn't reproduce your problem so far, in my test cases seems that Suds2Library doesn't use that much memory as you said. Maybe I'm looking in the wrong place, can you tell me what tool do you use to keep tracking memory performance or where can I see active clients running? Your test from above is too specific so I can't use it. Can you provide us an example that I can use and reproduce your problem?

**Comment by rticau** [comment]
Solved by PR https://github.com/rticau/Suds2Library/pull/2
